baseURL = 'https://edo.sh/'
languageCode = 'en-us'
title = 'cvengo bengo'
theme = 'terminal-dd'
copyright = 'Eduard Hopfer 2025'

[params]
showLanguageSelector = false
centerTheme = true
enableGitInfo = true
showLastUpdated = true
enablePostContent = false # whether to show a preview of a post at all
email = 'hopfere[at]proton[dot]me'

[languages]
  [languages.en]
    languageName = "English"
    title = "edo.sh-omepage"

    [languages.en.params]
      subtitle = "hoces malo koke"
      owner = "Eduard Hopfer"
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "edo.sh"
        logoHomeLink = "/"

  [languages.en.menu]
    [[languages.en.menu.main]]
        identifier = "portfolio"
        name = "portfolio"
        url = "/portfolio"
    [[languages.en.menu.main]]
        identifier = "posts"
        name = "posts"
        url = "/posts"
        # [[languages.en.menu.main]]
        #   identifier = "showcase"
        #   name = "Showcase"
        #   url = "/showcase"
